/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppTeamRouteImport } from './routes/app/team'
import { Route as AppTodayRouteImport } from './routes/app/today'
import { Route as AppVisitsRouteImport } from './routes/app/visits'
import { Route as AppClientsIndexRouteImport } from './routes/app/clients/index'
import { Route as AppClientsCustomerIdRouteImport } from './routes/app/clients/$customerId'
import { Route as AppClientsNewRouteImport } from './routes/app/clients/new'
import { Route as AppMarketIndexRouteImport } from './routes/app/market/index'
import { Route as AppMessagesIndexRouteImport } from './routes/app/messages/index'
import { Route as AppMessagesThreadIdRouteImport } from './routes/app/messages/$threadId'
import { Route as AppPayoutsIndexRouteImport } from './routes/app/payouts/index'
import { Route as AppPayoutsPeriodIdRouteImport } from './routes/app/payouts/$periodId'
import { Route as AppScheduleIndexRouteImport } from './routes/app/schedule/index'
import { Route as AppScheduleAppointmentIdRouteImport } from './routes/app/schedule/$appointmentId'
import { Route as AppScheduleNewRouteImport } from './routes/app/schedule/new'
import { Route as AppMarketGigsGigIdRouteImport } from './routes/app/market/gigs/$gigId'
import { Route as AppMarketGigsNewRouteImport } from './routes/app/market/gigs/new'
import { Route as AppMarketWorkersWorkerIdRouteImport } from './routes/app/market/workers/$workerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVisitsRoute = AppVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsCustomerIdRoute = AppClientsCustomerIdRouteImport.update({
  id: '/clients/$customerId',
  path: '/clients/$customerId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMarketIndexRoute = AppMarketIndexRouteImport.update({
  id: '/market/',
  path: '/market/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagesThreadIdRoute = AppMessagesThreadIdRouteImport.update({
  id: '/messages/$threadId',
  path: '/messages/$threadId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPayoutsIndexRoute = AppPayoutsIndexRouteImport.update({
  id: '/payouts/',
  path: '/payouts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPayoutsPeriodIdRoute = AppPayoutsPeriodIdRouteImport.update({
  id: '/payouts/$periodId',
  path: '/payouts/$periodId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScheduleIndexRoute = AppScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScheduleAppointmentIdRoute =
  AppScheduleAppointmentIdRouteImport.update({
    id: '/schedule/$appointmentId',
    path: '/schedule/$appointmentId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppScheduleNewRoute = AppScheduleNewRouteImport.update({
  id: '/schedule/new',
  path: '/schedule/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMarketGigsGigIdRoute = AppMarketGigsGigIdRouteImport.update({
  id: '/market/gigs/$gigId',
  path: '/market/gigs/$gigId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMarketGigsNewRoute = AppMarketGigsNewRouteImport.update({
  id: '/market/gigs/new',
  path: '/market/gigs/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMarketWorkersWorkerIdRoute =
  AppMarketWorkersWorkerIdRouteImport.update({
    id: '/market/workers/$workerId',
    path: '/market/workers/$workerId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/today': typeof AppTodayRoute
  '/app/visits': typeof AppVisitsRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$customerId': typeof AppClientsCustomerIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/messages/$threadId': typeof AppMessagesThreadIdRoute
  '/app/payouts/$periodId': typeof AppPayoutsPeriodIdRoute
  '/app/schedule/$appointmentId': typeof AppScheduleAppointmentIdRoute
  '/app/schedule/new': typeof AppScheduleNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/market/': typeof AppMarketIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/payouts/': typeof AppPayoutsIndexRoute
  '/app/schedule/': typeof AppScheduleIndexRoute
  '/app/market/gigs/$gigId': typeof AppMarketGigsGigIdRoute
  '/app/market/gigs/new': typeof AppMarketGigsNewRoute
  '/app/market/workers/$workerId': typeof AppMarketWorkersWorkerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/today': typeof AppTodayRoute
  '/app/visits': typeof AppVisitsRoute
  '/app': typeof AppIndexRoute
  '/app/clients/$customerId': typeof AppClientsCustomerIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/messages/$threadId': typeof AppMessagesThreadIdRoute
  '/app/payouts/$periodId': typeof AppPayoutsPeriodIdRoute
  '/app/schedule/$appointmentId': typeof AppScheduleAppointmentIdRoute
  '/app/schedule/new': typeof AppScheduleNewRoute
  '/app/clients': typeof AppClientsIndexRoute
  '/app/market': typeof AppMarketIndexRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/app/payouts': typeof AppPayoutsIndexRoute
  '/app/schedule': typeof AppScheduleIndexRoute
  '/app/market/gigs/$gigId': typeof AppMarketGigsGigIdRoute
  '/app/market/gigs/new': typeof AppMarketGigsNewRoute
  '/app/market/workers/$workerId': typeof AppMarketWorkersWorkerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/today': typeof AppTodayRoute
  '/app/visits': typeof AppVisitsRoute
  '/app/': typeof AppIndexRoute
  '/app/clients/$customerId': typeof AppClientsCustomerIdRoute
  '/app/clients/new': typeof AppClientsNewRoute
  '/app/messages/$threadId': typeof AppMessagesThreadIdRoute
  '/app/payouts/$periodId': typeof AppPayoutsPeriodIdRoute
  '/app/schedule/$appointmentId': typeof AppScheduleAppointmentIdRoute
  '/app/schedule/new': typeof AppScheduleNewRoute
  '/app/clients/': typeof AppClientsIndexRoute
  '/app/market/': typeof AppMarketIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/payouts/': typeof AppPayoutsIndexRoute
  '/app/schedule/': typeof AppScheduleIndexRoute
  '/app/market/gigs/$gigId': typeof AppMarketGigsGigIdRoute
  '/app/market/gigs/new': typeof AppMarketGigsNewRoute
  '/app/market/workers/$workerId': typeof AppMarketWorkersWorkerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/settings'
    | '/app/team'
    | '/app/today'
    | '/app/visits'
    | '/app/'
    | '/app/clients/$customerId'
    | '/app/clients/new'
    | '/app/messages/$threadId'
    | '/app/payouts/$periodId'
    | '/app/schedule/$appointmentId'
    | '/app/schedule/new'
    | '/app/clients/'
    | '/app/market/'
    | '/app/messages/'
    | '/app/payouts/'
    | '/app/schedule/'
    | '/app/market/gigs/$gigId'
    | '/app/market/gigs/new'
    | '/app/market/workers/$workerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/settings'
    | '/app/team'
    | '/app/today'
    | '/app/visits'
    | '/app'
    | '/app/clients/$customerId'
    | '/app/clients/new'
    | '/app/messages/$threadId'
    | '/app/payouts/$periodId'
    | '/app/schedule/$appointmentId'
    | '/app/schedule/new'
    | '/app/clients'
    | '/app/market'
    | '/app/messages'
    | '/app/payouts'
    | '/app/schedule'
    | '/app/market/gigs/$gigId'
    | '/app/market/gigs/new'
    | '/app/market/workers/$workerId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/settings'
    | '/app/team'
    | '/app/today'
    | '/app/visits'
    | '/app/'
    | '/app/clients/$customerId'
    | '/app/clients/new'
    | '/app/messages/$threadId'
    | '/app/payouts/$periodId'
    | '/app/schedule/$appointmentId'
    | '/app/schedule/new'
    | '/app/clients/'
    | '/app/market/'
    | '/app/messages/'
    | '/app/payouts/'
    | '/app/schedule/'
    | '/app/market/gigs/$gigId'
    | '/app/market/gigs/new'
    | '/app/market/workers/$workerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/visits': {
      id: '/app/visits'
      path: '/visits'
      fullPath: '/app/visits'
      preLoaderRoute: typeof AppVisitsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/clients'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/$customerId': {
      id: '/app/clients/$customerId'
      path: '/clients/$customerId'
      fullPath: '/app/clients/$customerId'
      preLoaderRoute: typeof AppClientsCustomerIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/new': {
      id: '/app/clients/new'
      path: '/clients/new'
      fullPath: '/app/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/market/': {
      id: '/app/market/'
      path: '/market'
      fullPath: '/app/market/'
      preLoaderRoute: typeof AppMarketIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/messages'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/messages/$threadId': {
      id: '/app/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/app/messages/$threadId'
      preLoaderRoute: typeof AppMessagesThreadIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payouts/': {
      id: '/app/payouts/'
      path: '/payouts'
      fullPath: '/app/payouts/'
      preLoaderRoute: typeof AppPayoutsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/payouts/$periodId': {
      id: '/app/payouts/$periodId'
      path: '/payouts/$periodId'
      fullPath: '/app/payouts/$periodId'
      preLoaderRoute: typeof AppPayoutsPeriodIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedule/': {
      id: '/app/schedule/'
      path: '/schedule'
      fullPath: '/app/schedule/'
      preLoaderRoute: typeof AppScheduleIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedule/$appointmentId': {
      id: '/app/schedule/$appointmentId'
      path: '/schedule/$appointmentId'
      fullPath: '/app/schedule/$appointmentId'
      preLoaderRoute: typeof AppScheduleAppointmentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schedule/new': {
      id: '/app/schedule/new'
      path: '/schedule/new'
      fullPath: '/app/schedule/new'
      preLoaderRoute: typeof AppScheduleNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/market/gigs/$gigId': {
      id: '/app/market/gigs/$gigId'
      path: '/market/gigs/$gigId'
      fullPath: '/app/market/gigs/$gigId'
      preLoaderRoute: typeof AppMarketGigsGigIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/market/gigs/new': {
      id: '/app/market/gigs/new'
      path: '/market/gigs/new'
      fullPath: '/app/market/gigs/new'
      preLoaderRoute: typeof AppMarketGigsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/market/workers/$workerId': {
      id: '/app/market/workers/$workerId'
      path: '/market/workers/$workerId'
      fullPath: '/app/market/workers/$workerId'
      preLoaderRoute: typeof AppMarketWorkersWorkerIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTodayRoute: typeof AppTodayRoute
  AppVisitsRoute: typeof AppVisitsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsCustomerIdRoute: typeof AppClientsCustomerIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppMessagesThreadIdRoute: typeof AppMessagesThreadIdRoute
  AppPayoutsPeriodIdRoute: typeof AppPayoutsPeriodIdRoute
  AppScheduleAppointmentIdRoute: typeof AppScheduleAppointmentIdRoute
  AppScheduleNewRoute: typeof AppScheduleNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppMarketIndexRoute: typeof AppMarketIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppPayoutsIndexRoute: typeof AppPayoutsIndexRoute
  AppScheduleIndexRoute: typeof AppScheduleIndexRoute
  AppMarketGigsGigIdRoute: typeof AppMarketGigsGigIdRoute
  AppMarketGigsNewRoute: typeof AppMarketGigsNewRoute
  AppMarketWorkersWorkerIdRoute: typeof AppMarketWorkersWorkerIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTodayRoute: AppTodayRoute,
  AppVisitsRoute: AppVisitsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsCustomerIdRoute: AppClientsCustomerIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppMessagesThreadIdRoute: AppMessagesThreadIdRoute,
  AppPayoutsPeriodIdRoute: AppPayoutsPeriodIdRoute,
  AppScheduleAppointmentIdRoute: AppScheduleAppointmentIdRoute,
  AppScheduleNewRoute: AppScheduleNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppMarketIndexRoute: AppMarketIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppPayoutsIndexRoute: AppPayoutsIndexRoute,
  AppScheduleIndexRoute: AppScheduleIndexRoute,
  AppMarketGigsGigIdRoute: AppMarketGigsGigIdRoute,
  AppMarketGigsNewRoute: AppMarketGigsNewRoute,
  AppMarketWorkersWorkerIdRoute: AppMarketWorkersWorkerIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
