/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CinefilosRouteImport } from './routes/cinefilos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedComunidadesRouteImport } from './routes/_authenticated/comunidades'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedDescobrirRouteImport } from './routes/_authenticated/descobrir'
import { Route as AuthenticatedListasRouteImport } from './routes/_authenticated/listas'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPessoasRouteImport } from './routes/_authenticated/pessoas'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedSessoesRouteImport } from './routes/_authenticated/sessoes'
import { Route as AuthenticatedChatMatchIdRouteImport } from './routes/_authenticated/chat.$matchId'
import { Route as AuthenticatedComunidadesSlugRouteImport } from './routes/_authenticated/comunidades.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CinefilosRoute = CinefilosRouteImport.update({
  id: '/cinefilos',
  path: '/cinefilos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunidadesRoute =
  AuthenticatedComunidadesRouteImport.update({
    id: '/comunidades',
    path: '/comunidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDescobrirRoute = AuthenticatedDescobrirRouteImport.update({
  id: '/descobrir',
  path: '/descobrir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListasRoute = AuthenticatedListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPessoasRoute = AuthenticatedPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessoesRoute = AuthenticatedSessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatMatchIdRoute =
  AuthenticatedChatMatchIdRouteImport.update({
    id: '/chat/$matchId',
    path: '/chat/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunidadesSlugRoute =
  AuthenticatedComunidadesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedComunidadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cinefilos': typeof CinefilosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/comunidades': typeof AuthenticatedComunidadesRouteWithChildren
  '/config': typeof AuthenticatedConfigRoute
  '/descobrir': typeof AuthenticatedDescobrirRoute
  '/listas': typeof AuthenticatedListasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/sessoes': typeof AuthenticatedSessoesRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/comunidades/$slug': typeof AuthenticatedComunidadesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cinefilos': typeof CinefilosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/comunidades': typeof AuthenticatedComunidadesRouteWithChildren
  '/config': typeof AuthenticatedConfigRoute
  '/descobrir': typeof AuthenticatedDescobrirRoute
  '/listas': typeof AuthenticatedListasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pessoas': typeof AuthenticatedPessoasRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/sessoes': typeof AuthenticatedSessoesRoute
  '/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/comunidades/$slug': typeof AuthenticatedComunidadesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cinefilos': typeof CinefilosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/comunidades': typeof AuthenticatedComunidadesRouteWithChildren
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/descobrir': typeof AuthenticatedDescobrirRoute
  '/_authenticated/listas': typeof AuthenticatedListasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/pessoas': typeof AuthenticatedPessoasRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/sessoes': typeof AuthenticatedSessoesRoute
  '/_authenticated/chat/$matchId': typeof AuthenticatedChatMatchIdRoute
  '/_authenticated/comunidades/$slug': typeof AuthenticatedComunidadesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cinefilos'
    | '/admin'
    | '/chats'
    | '/comunidades'
    | '/config'
    | '/descobrir'
    | '/listas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil'
    | '/pessoas'
    | '/premium'
    | '/sessoes'
    | '/chat/$matchId'
    | '/comunidades/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cinefilos'
    | '/admin'
    | '/chats'
    | '/comunidades'
    | '/config'
    | '/descobrir'
    | '/listas'
    | '/notificacoes'
    | '/onboarding'
    | '/perfil'
    | '/pessoas'
    | '/premium'
    | '/sessoes'
    | '/chat/$matchId'
    | '/comunidades/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cinefilos'
    | '/_authenticated/admin'
    | '/_authenticated/chats'
    | '/_authenticated/comunidades'
    | '/_authenticated/config'
    | '/_authenticated/descobrir'
    | '/_authenticated/listas'
    | '/_authenticated/notificacoes'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/pessoas'
    | '/_authenticated/premium'
    | '/_authenticated/sessoes'
    | '/_authenticated/chat/$matchId'
    | '/_authenticated/comunidades/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CinefilosRoute: typeof CinefilosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinefilos': {
      id: '/cinefilos'
      path: '/cinefilos'
      fullPath: '/cinefilos'
      preLoaderRoute: typeof CinefilosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidades': {
      id: '/_authenticated/comunidades'
      path: '/comunidades'
      fullPath: '/comunidades'
      preLoaderRoute: typeof AuthenticatedComunidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/descobrir': {
      id: '/_authenticated/descobrir'
      path: '/descobrir'
      fullPath: '/descobrir'
      preLoaderRoute: typeof AuthenticatedDescobrirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listas': {
      id: '/_authenticated/listas'
      path: '/listas'
      fullPath: '/listas'
      preLoaderRoute: typeof AuthenticatedListasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoas': {
      id: '/_authenticated/pessoas'
      path: '/pessoas'
      fullPath: '/pessoas'
      preLoaderRoute: typeof AuthenticatedPessoasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessoes': {
      id: '/_authenticated/sessoes'
      path: '/sessoes'
      fullPath: '/sessoes'
      preLoaderRoute: typeof AuthenticatedSessoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$matchId': {
      id: '/_authenticated/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof AuthenticatedChatMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidades/$slug': {
      id: '/_authenticated/comunidades/$slug'
      path: '/$slug'
      fullPath: '/comunidades/$slug'
      preLoaderRoute: typeof AuthenticatedComunidadesSlugRouteImport
      parentRoute: typeof AuthenticatedComunidadesRoute
    }
  }
}

interface AuthenticatedComunidadesRouteChildren {
  AuthenticatedComunidadesSlugRoute: typeof AuthenticatedComunidadesSlugRoute
}

const AuthenticatedComunidadesRouteChildren: AuthenticatedComunidadesRouteChildren =
  {
    AuthenticatedComunidadesSlugRoute: AuthenticatedComunidadesSlugRoute,
  }

const AuthenticatedComunidadesRouteWithChildren =
  AuthenticatedComunidadesRoute._addFileChildren(
    AuthenticatedComunidadesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedComunidadesRoute: typeof AuthenticatedComunidadesRouteWithChildren
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedDescobrirRoute: typeof AuthenticatedDescobrirRoute
  AuthenticatedListasRoute: typeof AuthenticatedListasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPessoasRoute: typeof AuthenticatedPessoasRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedSessoesRoute: typeof AuthenticatedSessoesRoute
  AuthenticatedChatMatchIdRoute: typeof AuthenticatedChatMatchIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedComunidadesRoute: AuthenticatedComunidadesRouteWithChildren,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedDescobrirRoute: AuthenticatedDescobrirRoute,
  AuthenticatedListasRoute: AuthenticatedListasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPessoasRoute: AuthenticatedPessoasRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedSessoesRoute: AuthenticatedSessoesRoute,
  AuthenticatedChatMatchIdRoute: AuthenticatedChatMatchIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CinefilosRoute: CinefilosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
