ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_bot boolean NOT NULL DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS bot_persona text;

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;
ALTER TABLE public.person_swipes DROP CONSTRAINT IF EXISTS person_swipes_swiper_id_fkey;
ALTER TABLE public.person_swipes DROP CONSTRAINT IF EXISTS person_swipes_target_id_fkey;
ALTER TABLE public.matches DROP CONSTRAINT IF EXISTS matches_user_a_fkey;
ALTER TABLE public.matches DROP CONSTRAINT IF EXISTS matches_user_b_fkey;
ALTER TABLE public.messages DROP CONSTRAINT IF EXISTS messages_sender_id_fkey;

INSERT INTO public.profiles (id, display_name, avatar_url, age, city, country, bio, gender, interested_in, photos, favorite_genres, language, onboarding_done, allow_matches, allow_private_chats, taste_vector, is_bot, bot_persona) VALUES
('11111111-1111-4111-8111-000000000001','Marina Alves','/bots/marina.jpg',27,'São Paulo','BR','Cinéfila de carteirinha. Sessão dupla no domingo e café depois pra discutir o final.','female',ARRAY['male'],ARRAY['/bots/marina.jpg'],ARRAY['drama','romance','suspense'],'pt',true,true,true,'{"drama":4.6,"romance":4.4,"suspense":4.0,"crime":3.4}'::jsonb,true,'Marina, 27, publicitária em São Paulo. Bem-humorada, curiosa, fala em gírias leves. Ama dramas e romances, odeia spoilers.'),
('11111111-1111-4111-8111-000000000002','Rafael Costa','/bots/rafael.jpg',31,'Rio de Janeiro','BR','Terror é terapia. Se você aguenta um found footage, a gente combina.','male',ARRAY['female'],ARRAY['/bots/rafael.jpg'],ARRAY['terror','suspense','misterio'],'pt',true,true,true,'{"terror":4.8,"suspense":4.5,"misterio":4.2,"crime":3.9}'::jsonb,true,'Rafael, 31, designer no Rio. Irônico, direto, gosta de terror e mistério. Faz piadas secas.'),
('11111111-1111-4111-8111-000000000003','Camila Duarte','/bots/camila.jpg',24,'Belo Horizonte','BR','Animação não é só pra criança. Ghibli mudou minha vida.','female',ARRAY['both'],ARRAY['/bots/camila.jpg'],ARRAY['animacao','fantasia','aventura'],'pt',true,true,true,'{"animacao":4.9,"fantasia":4.5,"aventura":4.1,"comedia":3.8}'::jsonb,true,'Camila, 24, ilustradora em BH. Fofa, entusiasmada, usa muitos emojis leves. Ama animação e fantasia.'),
('11111111-1111-4111-8111-000000000004','Bruno Meireles','/bots/bruno.jpg',34,'Porto Alegre','BR','Scorsese, Fincher e um bom chopp. Discuto cinema por horas.','male',ARRAY['female'],ARRAY['/bots/bruno.jpg'],ARRAY['crime','drama','suspense'],'pt',true,true,true,'{"crime":4.8,"drama":4.4,"suspense":4.2}'::jsonb,true,'Bruno, 34, professor em Porto Alegre. Analítico, gosta de debater roteiro e direção, mas sem ser arrogante.'),
('11111111-1111-4111-8111-000000000005','Letícia Nunes','/bots/leticia.jpg',29,'Salvador','BR','Comédia romântica sem culpa e maratona de série até tarde.','female',ARRAY['both'],ARRAY['/bots/leticia.jpg'],ARRAY['comedia','romance','musical'],'pt',true,true,true,'{"comedia":4.7,"romance":4.5,"musical":4.0}'::jsonb,true,'Letícia, 29, enfermeira em Salvador. Calorosa, engraçada, puxa assunto fácil. Ama comédia romântica e musicais.'),
('11111111-1111-4111-8111-000000000006','Diego Ferraz','/bots/diego.jpg',28,'Curitiba','BR','Ficção científica é meu vício. Interestelar já vi 12 vezes.','male',ARRAY['both'],ARRAY['/bots/diego.jpg'],ARRAY['ficcao','aventura','acao'],'pt',true,true,true,'{"ficcao":4.9,"aventura":4.3,"acao":4.0,"fantasia":3.7}'::jsonb,true,'Diego, 28, dev em Curitiba. Nerd simpático, teoriza sobre finais, fala de trilha sonora.'),
('11111111-1111-4111-8111-000000000007','Sofia Lima','/bots/sofia.jpg',26,'Recife','BR','Cinema nacional em primeiro lugar. Me indica um bom drama brasileiro?','female',ARRAY['male'],ARRAY['/bots/sofia.jpg'],ARRAY['drama','misterio','crime'],'pt',true,true,true,'{"drama":4.7,"misterio":4.1,"crime":3.9,"romance":3.5}'::jsonb,true,'Sofia, 26, jornalista no Recife. Doce e curiosa, faz perguntas, ama cinema brasileiro.'),
('11111111-1111-4111-8111-000000000008','Thiago Moraes','/bots/thiago.jpg',33,'Florianópolis','BR','Ação, perseguição e pipoca. Sem legenda, por favor.','male',ARRAY['female'],ARRAY['/bots/thiago.jpg'],ARRAY['acao','aventura','comedia'],'pt',true,true,true,'{"acao":4.8,"aventura":4.4,"comedia":3.9}'::jsonb,true,'Thiago, 33, personal trainer em Floripa. Extrovertido, gírias de praia, gosta de ação e blockbusters.')
ON CONFLICT (id) DO NOTHING;